version: '3'
services:
  db:
    # This is a nonproduction app, no need to use postgres
    image: nouchka/sqlite3
    volumes:
      - ./tmp/db:/var/lib/sqlite3/data

  web:
    build: .
    environment:
      RAILS_ENV: development
      command: bash -c "rm -f /myapp/tmp/pids/server.pid && \
                        bundle exec rails db:migrate && \
                        bundle exec rails db:seed && \
                        ./bin/webpack-dev-server & \
                        bundle exec rails server -p 3000 -b '0.0.0.0'"

    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

